# Generated by Django 2.2.4 on 2019-12-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255, unique=True, verbose_name='Raison sociale')),
                ('street', models.CharField(max_length=255, null=True, verbose_name='Rue')),
                ('cp', models.IntegerField(null=True, verbose_name='Code postal')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Ville')),
                ('siret', models.IntegerField(null=True, verbose_name='SIRET')),
            ],
            options={
                'verbose_name': 'Exploitation agricole',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='Nom du produit')),
                ('international_codification', models.CharField(max_length=255, null=True, verbose_name='Codification internationale')),
                ('unit', models.CharField(max_length=255, null=True, verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='ProductFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_name', models.CharField(max_length=255, null=True, verbose_name='Nom spécifique')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ManyToManyField(related_name='_product_farmer_+', through='api_rest.ProductFarmer', to='api_rest.Farmer'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255, unique=True, verbose_name='Nom du certificat')),
                ('certificate_type', models.CharField(choices=[('bio', 'Biologique'), ('ogm', 'Sans OGM'), ('or', 'Origine')], default='bio', max_length=255, verbose_name='type')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Farmer')),
            ],
            options={
                'verbose_name': 'Certificat',
            },
        ),
    ]
