# Generated by Django 2.2.4 on 2019-12-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_auto_20191221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ManyToManyField(related_name='farmer', through='api_rest.ProductFarmer', to='api_rest.Farmer'),
        ),
    ]
