# Generated by Django 2.2.4 on 2019-12-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_auto_20191221_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfarmer',
            name='special_name',
        ),
    ]
