# Generated by Django 2.2.4 on 2019-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_remove_productfarmer_special_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfarmer',
            name='special_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom spécifique'),
        ),
    ]
