# Generated by Django 2.2.4 on 2019-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_productfarmer_special_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ManyToManyField(related_name='products', through='api_rest.ProductFarmer', to='api_rest.Farmer'),
        ),
    ]
